NODE1_IP="192.168.2.2"
NODE2_IP="192.168.2.3"

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/my_id_rsa.pub"
  config.vm.provision "shell", inline: "cat ~/.ssh/my_id_rsa.pub >> ~/.ssh/authorized_keys", privileged: false

  config.vm.define "node1" do |node1|
      node1.vm.network "private_network", ip: NODE1_IP
      node1.vm.provider "virtualbox" do |v|
          v.memory = 2048
          v.cpus = 2
          v.name = "vagrant-centos7-x2-1-"+NODE1_IP
      end
  end

  config.vm.define "node2" do |node2|
      node2.vm.network "private_network", ip: NODE2_IP
      node2.vm.provider "virtualbox" do |v|
          v.memory = 2048
          v.cpus = 2
          v.name = "vagrant-centos7-x2-2-"+NODE2_IP
      end

  end
end
