folderName = dirname = File.basename(Dir.getwd)
tld="vagrant.local"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/my_id_rsa.pub"
  config.vm.provision "shell", inline: "cat ~/.ssh/my_id_rsa.pub >> ~/.ssh/authorized_keys", privileged: false

  config.landrush.enabled = true
  config.landrush.tld = tld

  (1..5).each do |i|
  config.vm.define "node-#{i}" do |node|
    hostName=folderName+"-#{i}."+tld
    node.vm.hostname = hostName
      node.vm.network "private_network", type: "dhcp"
      node.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
        v.name = hostName
      end
    end
  end


end
