NODE1_IP="192.168.5.12"
NODE2_IP="192.168.5.13"
NODE3_IP="192.168.5.14"
NODE4_IP="192.168.5.15"
NODE5_IP="192.168.5.16"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/my_id_rsa.pub"
  config.vm.provision "shell", inline: "cat ~/.ssh/my_id_rsa.pub >> ~/.ssh/authorized_keys", privileged: false

  config.vm.define "node1" do |node1|
      node1.vm.network "private_network", ip: NODE1_IP
      node1.vm.provider "virtualbox" do |v|
          v.memory = 8192
          v.cpus = 4
          v.name = "vagrant-ubuntu1804-x5-1-"+NODE1_IP
      end
  end

  config.vm.define "node2" do |node2|
      node2.vm.network "private_network", ip: NODE2_IP
      node2.vm.provider "virtualbox" do |v|
          v.memory = 8192
          v.cpus = 4
          v.name = "vagrant-ubuntu1804-x5-2-"+NODE2_IP
      end
  end

  config.vm.define "node3" do |node3|
      node3.vm.network "private_network", ip: NODE3_IP
      node3.vm.provider "virtualbox" do |v|
          v.memory = 8192
          v.cpus = 4
          v.name = "vagrant-ubuntu1804-x5-3-"+NODE3_IP
      end
  end

  config.vm.define "node4" do |node4|
      node4.vm.network "private_network", ip: NODE4_IP
      node4.vm.provider "virtualbox" do |v|
          v.memory = 8192
          v.cpus = 4
          v.name = "vagrant-ubuntu1804-x5-4-"+NODE4_IP
      end
  end

  config.vm.define "node5" do |node5|
      node5.vm.network "private_network", ip: NODE5_IP
      node5.vm.provider "virtualbox" do |v|
          v.memory = 8192
          v.cpus = 4
          v.name = "vagrant-ubuntu1804-x5-5-"+NODE5_IP
      end
  end

end
