folderName = dirname = File.basename(Dir.getwd)

Vagrant.configure("2") do |config|
  config.landrush.tld = 'vagrant.local'
  config.vm.hostname = folderName+".vagrant.local"
  config.landrush.enabled = true

  config.vm.box = "centos/7"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
    v.cpus = 4
    v.name = "vagrant-centos-"+folderName
  end

  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/my_id_rsa.pub"
  config.vm.provision "shell", inline: "cat ~/.ssh/my_id_rsa.pub >> ~/.ssh/authorized_keys", privileged: false

end