folderName = dirname = File.basename(Dir.getwd)
tld="vagrant.local"

# Set folder name as the prefix of hostname
# You can manually set the hostnames for each vm
hostName1=folderName+"-1."+tld
hostName2=folderName+"-2."+tld


Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/my_id_rsa.pub"
  config.vm.provision "shell", inline: "cat ~/.ssh/my_id_rsa.pub >> ~/.ssh/authorized_keys", privileged: false

  config.landrush.enabled = true
  config.landrush.tld = tld

  config.vm.define "node1" do |node1|
      node1.vm.hostname = hostName1
      node1.vm.network "private_network", type: "dhcp"
      node1.vm.provider "virtualbox" do |v|
          v.memory = 2048
          v.cpus = 2
          v.name = hostName1
      end
  end

  config.vm.define "node2" do |node2|
      node2.vm.hostname = hostName2
      node2.vm.network "private_network", type: "dhcp"
      node2.vm.provider "virtualbox" do |v|
          v.memory = 2048
          v.cpus = 2
          v.name = hostName2
      end

  end
end
